[package]
name = "example-diesel"
version = "0.0.0"
edition = "2018"
resolver = "2"
authors = ["Michael P. Jung <michael.jung@terreon.de>"]
publish = false

[dependencies]
deadpool-diesel = { path = "../../crates/deadpool-diesel", features = ["postgres"] }
dotenvy = "0.15"
thiserror = "2.0"
